---

- name: Update server packages
  hosts: "{{inventory}}"
  become: yes

  tasks:

    - name: Update server packages
      apt:
        name: "*"
        state: latest
        update_cache: yes
        autoclean: yes
        autoremove: yes
